### ISSUE TITLE
Can the relevant model weights be disclosed?

### ISSUE THREAD

**Issue by zicai-danhuatang** [haformer/haformer#1]
I noticed that your paper “HAformer: Semantic fusion of hex machine code and assembly code for cross-architecture binary vulnerability detection”has been publicly published in Computers & Security(COSE). And I am very interested in this paper. But the model weights have not been made public. Can you provide the relevant weights of your model? If possible, I would greatly appreciate it.

**Comment by haformer** [comment]
The model weights for HAformer have been updated.
